dependencies:
- name: zookeeper
  version: 2.1.1
  repository: "file://../zookeeper"
  condition: zookeeper.enabled
- name: mysqlha
  version: 1.0.0
  repository: "file://../mysqlha"
  condition: mysql.enabled
