dependencies:
- name: zookeeper
  version: 2.1.1
  repository: "file://../zookeeper"
  condition: zookeeper.enabled
- name: mysql
  version: 1.4.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mysql.enabled
